AllCops:
  Exclude:
    - 'bin/*'
    - 'spec/test_projects/**/*.rb'
    - 'spec/lib/domain/source_examples/*.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/tasks/**/*.rake'
    - 'mudguard.gemspec'

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/HashEachMethods:
    Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/LineLength:
  Description: 'Limit lines to 100 characters.'
  Max: 100
