AllCops:
  Exclude:
    - 'bin/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/tasks/**/*.rake'
    - 'db/schema.rb'

Layout/LineLength:
  Description: 'Limit lines to 100 characters.'
  Max: 100
  Exclude:
    - 'features/step_definitions/**/*_steps.rb'

Style/Documentation:
  Exclude:
    - 'db/migrate/*.rb'
    - 'spec/**/*.rb'