version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler:2.1.4
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps

  linting:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler:2.1.4
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop

  testing:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler:2.1.4
      - ruby/install-deps
      - ruby/rspec-test
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - linting
      - testing