#!/usr/bin/env ruby
# frozen_string_literal: true

require "mudguard/infrastructure/cli/view"
require "mudguard/infrastructure/cli/controller"

# Checks the dependencies of a ruby project
module Mudguard
  view = Mudguard::Infrastructure::Cli::View.new
  parser = Mudguard::Infrastructure::Cli::Controller.new(view: view)
  ok = parser.parse!(ARGV)
  exit(ok ? 0 : 1)
end
